spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/intelliJ-workspace/car_company
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    #쿼리파라미터 남기기